# In this scenario, the node must have a label with the key topology.kubernetes.io/zone and the value of that label must be us-central1-b.
# and The node preferably has a label with the key env and the value will be dev and the node preferably has a label with the key app and the value will be run . 
# Here the in preferred condition, Nodes with the highest total score are prioritized when the scheduler makes a scheduling decision for the Pod. 
apiVersion: v1
kind: Pod
metadata:
  name: node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-central1-b
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 5
        preference:
          matchExpressions:
          - key: env
            operator: In
            values:
            - dev
      - weight: 1
        preference:
          matchExpressions:
          - key: app
            operator: In
            values: 
            - run
  containers:
  - image: nginx
    name: nginx 
